USER_HOME=$(eval echo "~$USER")

PERCIV_ROS_DOMAIN_ID=201
PERCIV_PYTHON_VERSION="python3.8"
PERCIV_WS_PATH="$USER_HOME/perciv_ws"
PERCIV_VENV_PATH="$USER_HOME/perciv_venv"
PERCIV_VENV_SOURCE_PATH="$PERCIV_VENV_PATH/bin/activate"
PERCIV_NAV_WS_PATH="$USER_HOME/perciv_navigation_ws"